import java.awt.Desktop;
import java.awt.Toolkit;
import java.net.URI;
import javax.swing.JOptionPane;



public class Home extends javax.swing.JFrame {


    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setTitle("Desktop Search");
        setSize(600 , 500);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 170, 360, 33);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(0, 17, 213));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 220, 70, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahoo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 220, 70, 70);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neil\\Documents\\NetBeansProjects\\GoogleHome\\src\\Bing.png")); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 220, 70, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wikipedia.png"))); // NOI18N
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 220, 70, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facebook.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(460, 300, 70, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Copyright 2014 , All Rights Reserved");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 390, 210, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 170, 52, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Search People");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 320, 110, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 320, 247, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
      if (jTextField1.getText().equals(""))
      {
          JOptionPane.showMessageDialog(null, "Please enter some text");
      
          }
     else
      {
      String query = jTextField1.getText();
      query =  query.replaceAll(" ", "+");
          
          
          if(Desktop.isDesktopSupported())
          {
              
              try {
                  Desktop.getDesktop().browse(new URI
                                ("http://www.google.co.in/search?q="+query+"&oq="+query+""));
              }
              
              catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, ex);
              }
          }
      }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        
      if (jTextField1.getText().equals(""))
      {
          JOptionPane.showMessageDialog(null, "Please enter some text");
      
          }
     else
      {
      String query = jTextField1.getText();
      query =  query.replaceAll(" ", "+");
          
          if(Desktop.isDesktopSupported())
          {
              
              try {
                  Desktop.getDesktop().browse(new URI
("http://in.search.yahoo.com/search?ei=UTF-8&fr=crmas&p="+query+""));
              }
              
              catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, ex);
              }
          }
      }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

            
      if (jTextField2.getText().equals(""))
      {
          JOptionPane.showMessageDialog(null, "Please enter some text");
      
          }
     else
      {
      String query = jTextField2.getText();
      query =  query.replaceAll(" ", "+");
          
          if(Desktop.isDesktopSupported())
          {
              
              try {
                  Desktop.getDesktop().browse(new URI
        ("https://www.facebook.com/search/str/"+query+"/users-named"));
              }
              
              catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, ex);
              }
          }
      }
        
    
           }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
